services:
    backend_service:
        container_name: backend
        build: ./backend/
        command: [ "poetry", "run", "uvicorn", "app.main:app", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000" ]
        ports:
            - "8000:8000"
        # volumes:
        #     - ./:/backend/
        # restart: always
        # env_file:
        #     - ./app/.env
        # depends_on:
        #     - db_service


    frontend_service:
        container_name: frontend
        build: ./frontend/
        command: [ "npm", "start", "--port", "3000" ]
        ports:
            - 3000:3000
        depends_on:
            - backend_service
    # db_service:

    # nginx:
    #     image: nginx:latest
    #     ports:
    #         - "8080:8080"
    #     volumes:
    #         - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - backend
    #         - frontend
