version: '2.3'

services:
    backend:
        container_name: backend
        build: ./backend/
        ports:
            - 8000:8000
        # volumes:
        #     - ./:/backend/
        # restart: always
        # env_file:
        #     - ./app/.env
        # depends_on:
        #     - frontend

        # frontend:
        #     container_name: frontend
        #     build: ./frontend/
        #     ports:
        #         - 3000:3000
        # nginx:
        #     image: nginx:latest
        #     ports:
        #         - "8080:8080"
        #     volumes:
        #         - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
        #     depends_on:
        #         - backend
        #         - frontend
